#!/bin/sh
# -*- coding: utf-8 -*-
# Author: Pär Andersson  (National Supercomputer Centre, Sweden)
# Version: 0.2 2007-07-30
#
# Simple batch script that starts SCREEN.
# MYDIR is passed in as an environment variable

exec screen -c "${MYDIR}"/sinteractive_screenrc.conf -Dm -S "slurm$SLURM_JOB_ID"

